# Generated by Django 5.2.8 on 2025-11-20 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=10)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.CharField(default=django.utils.timezone.now, max_length=10)),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('votos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Playlist',
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('artista', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('duracion', models.IntegerField()),
                ('memoria', models.FloatField()),
                ('calidad', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='core.administrador')),
            ],
            options={
                'db_table': 'Cancion',
            },
        ),
        migrations.CreateModel(
            name='CarritoCancion',
            fields=[
                ('id_carrito_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_cancion', to='core.cancion')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='core.carrito')),
            ],
            options={
                'db_table': 'CarritoCancion',
            },
        ),
        migrations.CreateModel(
            name='CompraCancion',
            fields=[
                ('id_compra_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_cancion', to='core.cancion')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_canciones', to='core.compra')),
            ],
            options={
                'db_table': 'CompraCancion',
            },
        ),
        migrations.AddField(
            model_name='administrador',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='core.persona'),
        ),
        migrations.CreateModel(
            name='ContenidoPlaylist',
            fields=[
                ('id_contenido_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_playlist', to='core.cancion')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.playlist')),
            ],
            options={
                'db_table': 'ContenidoPlaylist',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.compra')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.persona')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('id_vinilo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('imagen_caratula', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinilos', to='core.usuario')),
            ],
            options={
                'db_table': 'Vinilo',
            },
        ),
        migrations.CreateModel(
            name='ContenidoVinilos',
            fields=[
                ('id_contenido_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_vinilos', to='core.cancion')),
                ('vinilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.vinilo')),
            ],
            options={
                'db_table': 'ContenidoVinilos',
            },
        ),
        migrations.CreateModel(
            name='CompraVinilo',
            fields=[
                ('id_compra_vinilo', models.AutoField(primary_key=True, serialize=False)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_vinilos', to='core.compra')),
                ('vinilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_vinilo', to='core.vinilo')),
            ],
            options={
                'db_table': 'CompraVinilo',
            },
        ),
        migrations.CreateModel(
            name='CarritoVinilo',
            fields=[
                ('id_carrito_vinilo', models.AutoField(primary_key=True, serialize=False)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinilos', to='core.carrito')),
                ('vinilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_vinilo', to='core.vinilo')),
            ],
            options={
                'db_table': 'CarritoVinilo',
            },
        ),
    ]
