# Generated by Django 5.2.8 on 2025-11-21 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_registro',
            field=models.CharField(default=django.utils.timezone.now),
        ),
    ]
