# Generated by Django 5.2.8 on 2025-11-21 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_persona_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_registro',
            field=models.CharField(default=django.utils.timezone.localdate),
        ),
    ]
