# Generated by Django 5.2.8 on 2025-11-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_persona_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='cancion/'),
        ),
    ]
