# Generated by Django 5.2.8 on 2025-11-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cancion_caratula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='calidad',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='memoria',
        ),
    ]
