# Generated by Django 5.2.8 on 2025-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cancion_calidad_remove_cancion_memoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
