# Generated by Django 5.2.8 on 2025-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cancion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
