# Generated by Django 5.2.8 on 2025-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_persona_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinilo',
            name='imagen_caratula',
        ),
        migrations.AddField(
            model_name='vinilo',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='vinilo/'),
        ),
    ]
