# Generated by Django 5.2.8 on 2025-11-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_vinilo_imagen_caratula_vinilo_caratula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidovinilos',
            name='id_contenido_playlist',
        ),
        migrations.AddField(
            model_name='contenidovinilos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='vinilo',
            name='canciones',
            field=models.ManyToManyField(through='core.ContenidoVinilos', to='core.cancion'),
        ),
        migrations.AlterField(
            model_name='contenidovinilos',
            name='cancion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='core.cancion'),
        ),
    ]
