"""Creación inicial de tablas

Revision ID: c2403272a8b9
Revises: 
Create Date: 2025-10-16 19:43:58.664101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2403272a8b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Persona',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('Administrador',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_admin')
    )
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('Cancion',
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('artista', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('memoria', sa.Float(), nullable=False),
    sa.Column('calidad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['Administrador.id_admin'], ),
    sa.PrimaryKeyConstraint('id_cancion')
    )
    op.create_table('Compra',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('Playlist',
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('votos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lista')
    )
    op.create_table('Vinilo',
    sa.Column('id_vinilo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('imagen_caratula', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_vinilo')
    )
    op.create_table('CompraCancion',
    sa.Column('id_compra_cancion', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_cancion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cancion'], ['Cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_compra'], ['Compra.id_compra'], ),
    sa.PrimaryKeyConstraint('id_compra_cancion')
    )
    op.create_table('CompraVinilo',
    sa.Column('id_compra_vinilo', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_vinilo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['Compra.id_compra'], ),
    sa.ForeignKeyConstraint(['id_vinilo'], ['Vinilo.id_vinilo'], ),
    sa.PrimaryKeyConstraint('id_compra_vinilo')
    )
    op.create_table('ContenidoPlaylist',
    sa.Column('id_contenido_playlist', sa.Integer(), nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=True),
    sa.Column('id_cancion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cancion'], ['Cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_lista'], ['Playlist.id_lista'], ),
    sa.PrimaryKeyConstraint('id_contenido_playlist')
    )
    op.create_table('ContenidoVinilos',
    sa.Column('id_contenido_playlist', sa.Integer(), nullable=False),
    sa.Column('id_vinilo', sa.Integer(), nullable=True),
    sa.Column('id_cancion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cancion'], ['Cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_vinilo'], ['Vinilo.id_vinilo'], ),
    sa.PrimaryKeyConstraint('id_contenido_playlist')
    )
    op.create_table('Resena',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['Compra.id_compra'], ),
    sa.PrimaryKeyConstraint('id_resena')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resena')
    op.drop_table('ContenidoVinilos')
    op.drop_table('ContenidoPlaylist')
    op.drop_table('CompraVinilo')
    op.drop_table('CompraCancion')
    op.drop_table('Vinilo')
    op.drop_table('Playlist')
    op.drop_table('Compra')
    op.drop_table('Cancion')
    op.drop_table('Usuario')
    op.drop_table('Administrador')
    op.drop_table('Persona')
    # ### end Alembic commands ###
